### ISSUE TITLE
npm ci fails with "Error: write after end" or "ERR_STREAM_WRITE_AFTER_END"

### ISSUE THREAD

**Issue by toniton** [resin-io-modules/rendition#503]
**Describe the bug**
NPM crashes and fail after I clone the project rendition and run `npm ci`. 

**To Reproduce**
1. Clone the project'
2. Run `npm ci` from the project directory.

**Expected behavior**
The project is supposed to build, so that I can include it in my project to use the components.

**Screenshots**
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:572:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/libcipm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:185:15)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:301:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:252:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:165:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:180:13)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:301:25)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:102:17)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:239:10)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
events.js:165░░░░░░⸩ ⠋ extractTree: sill extractTree jsonfile@4.0.0 -> /Users/Toni/Documents/nodejs/rendition/node_modules/ts-jest/node_modules/jsonfile
      throw er; // Unhandled 'error' event

```

**Specifications (please complete the following information):**
  - OS: OSX 10.13.5
  - Node: v9.8.0
  - NPM: v6.1.0

*Before submitting this issue, please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by thgreasi** [comment]
Hi @toniton, can you please try doing the same using a stable node version. I can confirm that it work for me on node v8.11.3 with npm v6.2.0 . It also seems to work on travis-ci with node 6 & npm 5.8.0.

**Comment by toniton** [comment]
@thgreasi I believe to use this project, I have to 

`npm install https://github.com/resin-io-modules/rendition.git`

and then do

`import { Button, Box, Provider } from 'rendition';`

***These does not work as expected***, as there is as dist & src folders have been ignored at .git/.npm level.
Are there any other alternatives I could use to install this library?

**Comment by thgreasi** [comment]
@toniton rendition is published on npm so you should do `npm install rendition --save` instead of the git repo. Is this solving the issue for you?

**Comment by LucianBuzzo** [comment]
@toniton The build output is generated automatically prior to deployment to npm as part of our CI process. This is a common pattern for npm modules as it means that we don't have to recompile and commit build files with every change.
As a result of this we don't support using rendition as a git dependency, please use `npm install rendition` instead.

**Comment by toniton** [comment]
Ok, thanks for the clarification @LucianBuzzo. @thgreasi would do `npm install` now.

**Comment by LucianBuzzo** [comment]
@toniton I opened a PR here https://github.com/resin-io-modules/rendition/pull/504
